app/Http/routes.php
<?php
//Common Routes
Route::when('*', ['middleware' => 'csrf'], ['POST', 'PUT', 'PATCH', 'DELETE']);

Route::get('/',['as' => 'home','uses'=>'tune_orbit_bo\DashboardController@index','middleware'=>'auth']);

//Auth
Route::group(['namespace'=>'Auth'], function () {
  Route::get('login',['as' => 'login','uses'=>'AuthController@showLogin']);
  Route::post('login',['as' => 'postLogin','uses'=>'AuthController@doLogin']);
  Route::get('sign_out',['as' => 'sign_out','uses'=>'AuthController@signOut']);
});

//tune_orbit-bo  Routes
Route::group(['prefix'=>'tune_orbit_bo','namespace'=>'tune_orbit_bo','middleware'=>'auth'],function(){
  //Dashboard
  Route::get('dashboard',['as' => 'dashboard','uses'=>'DashboardController@index']);



  //Service Page
  Route::group(['prefix'=>'service_page','namespace'=>'service_page'],function(){

    //Services
   Route::resource('services','ServicePageController');

   Route::post('/update_new_service_page/{services_id}', ['as' => 'service_page.services.updateServicePage', 'uses' => 'ServicePageController@updateServicePage']);
   Route::get('/get_specific_subservices/{services_id}', ['as' => 'service_page.services.getspecificSubservices', 'uses' => 'ServicePageController@getspecificSubservices']);
   Route::get('/serviceImg_delete/', ['as' => 'service_page.services.deleteSpecificImg', 'uses' => 'ServicePageController@deleteSpecificImg']);
   Route::get('/servicePagePhoto_delete/', ['as' => 'service_page.services.deleteSpecificServicePagePhoto', 'uses' => 'ServicePageController@deleteSpecificServicePagePhoto']);

   Route::resource('view_and_commit','ViewCommitController');
   Route::put('/update_service_page/{services_id}', ['as' => 'service_page.view_and_commit.updateServicePage', 'uses' => 'ViewCommitController@updateServicePage']);

   Route::resource('audit_and_commit','AuditCommitController');
   Route::post('/audit_and_commit/{audit_checkpoint_id}/{user_service_id}', ['as' => 'getspecificServiceAuditRemark', 'uses' => 'AuditCommitController@getspecificRemark']);
   Route::post('/updateOpenHours', ['as' => 'updateOpenHours', 'uses' => 'AuditCommitController@updateOpenHours']);

      Route::resource('manage_services','ManageServicePageController');
    Route::post('/manage_services/filter', ['as' => 'service_page.manage_services.filter', 'uses' => 'ManageServicePageController@filter']);

      Route::post('/update_manage_service_page/{services_id}', ['as' => 'service_page.manage_services.updateServicePage', 'uses' => 'ManageServicePageController@updateServicePage']);

      Route::get('/manage_services/push_pull_service/{services_id}', ['as' => 'service_page.manage_services.push_pull_service', 'uses' => 'ManageServicePageController@push_pull_service']);
 });

  Route::group(['prefix'=>'excel_import','namespace'=>'excel_import'],function(){

    //Services
   Route::resource('import','ExcelImportController');

   Route::post('/uploadExcel/', ['as' => 'tune_orbit_bo.excel_import.import.uploadExcel', 'uses' => 'ExcelImportController@uploadExcel']);

 });

//Masters
  Route::group(['prefix'=>'masters','namespace'=>'masters'],function(){

    //Services
   Route::resource('services','ServicesController');

   Route::post('/upload/', ['as' => 'tune_orbit_bo.masters.services.uploadImg', 'uses' => 'ServicesController@uploadImg']);

   Route::put('/uploadImage/', ['as' => 'tune_orbit_bo.masters.services.uploadImgForEdit', 'uses' => 'ServicesController@uploadImgForEdit']);

   Route::get('/delete_image/', ['as' => 'tune_orbit_bo.masters.services.deleteServiceImage', 'uses' => 'ServicesController@deleteServiceImage']);

   Route::get('/services/deactivate/{services_id}', ['as' => 'masters.services.deactivate', 'uses' => 'ServicesController@deactivate']);



    //Sub Services
   Route::resource('sub_services','SubServicesController');
   
   Route::get('/sub_services/deactivate/{sub_services_id}', ['as' => 'masters.sub_services.deactivate', 'uses' => 'SubServicesController@deactivate']); 

   Route::get('/sub_services/manage_gallery/{sub_services_id}', ['as' => 'masters.sub_services.manage_gallery', 'uses' => 'SubServicesController@manage_gallery']); 


   Route::post('/sub_services/{sub_services_id}', ['as' => 'sub_services.updateServiceImages', 'uses' => 'SubServicesController@updateServiceImages']);

   Route::get('/serviceImg_delete/', ['as' => 'masters.sub_services.deleteSpecificServiceImg', 'uses' => 'SubServicesController@deleteSpecificServiceImg']);

   Route::post('/upload_serviceImg/', ['as' => 'tune_orbit_bo.masters.sub_services.uploadserviceImg', 'uses' => 'SubServicesController@uploadserviceImg']);

   Route::post('/edit_upload_serviceImg/', ['as' => 'tune_orbit_bo.masters.sub_services.editUploadserviceImg', 'uses' => 'SubServicesController@editUploadserviceImg']);




 });



});

function getDateDifferenceInDays($date1,$date2){
  $date1=new Date($date1);
  $date2=new Date($date2);
  $diff = new Date($date1 - $date2);
  $days = $diff/1000/60/60/24;
  $x=($days.toString()).split('.');
  return $x[0];
}

function getFormatedDate($date){
  $formated_date=date("d F Y",strtotime($date));
  return $formated_date;
}


function getServiceUploadedTmpPath($file){
  $file_path='';
  if (App::environment('local')) {
    $file_path='/tune_orbit_bo/image/tmp/'.$file;
  } else{
    $file_path=ENV('DOMAIN_PATH').'/backoffice/tune_orbit_bo/image/tmp/'.$file;
  }
  return $file_path;
}

function getServicesDestinationPathToStore(){
  $file_path='';
  if (App::environment('local')) {
    $file_path='../../../dev/tune_orbit_web/app/images/services/';
  } else{
    $file_path=ENV('DOMAIN_PATH').'../images/services/';
  }
  return $file_path;
}


function getServicesUploadedPath($file){
  $file_path='';
  if (App::environment('local')) {
    $file_path='../../../dev/tune_orbit_web/app'.$file;
  } else{
    $file_path=ENV('DOMAIN_PATH').$file;
  }
  return $file_path;
}


function getSubServiceUploadedTmpPath($file){
  $file_path='';
  if (App::environment('local')) {
    $file_path='/tune_orbit_bo/image/tmp/'.$file;
  } else{
    $file_path=ENV('DOMAIN_PATH').'/backoffice/tune_orbit_bo/image/tmp/'.$file;
  }
  return $file_path;
}


function getServicesPageBannerPath(){
  $file_path='';
  if (App::environment('local')) {
    $file_path='/tune_orbit_bo/image/service_page_images/banner';
  } else{
    $file_path=ENV('DOMAIN_PATH');
  }
  return $file_path;
}

function getServicesPageThumbnailPath(){
  $file_path='';
  if (App::environment('local')) {
    $file_path='/tune_orbit_bo/image/service_page_images/thumbnail';
  } else{
    $file_path=ENV('DOMAIN_PATH');
  }
  return $file_path;
}

function getServicesPagePhotoPath(){
  $file_path='';
  if (App::environment('local')) {
    $file_path='/tune_orbit_bo/image/service_page_images';
  } else{
    $file_path=ENV('DOMAIN_PATH').'/tune_orbit_bo/image/services/'.$file;
  }
  return $file_path;
}

app/Http/Controllers/tune_orbit_bo/DashboardController.php
<?php

namespace App\Http\Controllers\tune_orbit_bo;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use DB;

class DashboardController extends Controller
{
    public function index()
    {
        $total_services=DB::table('user_services as us')->whereNull('us.deleted_at')->count();
        $pending_commit=DB::table('user_services as us')->where('us.commit_flag',0)->count();
        $pending_audit=DB::table('user_services as us')->where('us.commit_flag',1)->where('us.audit_flag',0)->count();
        $service_in_website=DB::table('user_services as us')->where('us.in_website',1)->count();
        $unaudited_service_in_website=DB::table('user_services as us')->where('us.in_website',1)->where('us.audit_flag',0)->count();
        // dd($total_services);
        return view('tune_orbit_bo.dashboard.index')->with('total_services',$total_services)->with('pending_commit',$pending_commit)->with('pending_audit',$pending_audit)->with('service_in_website',$service_in_website)->with('unaudited_service_in_website',$unaudited_service_in_website);
    }
}

app/Http/Controllers/tune_orbit_bo/excel_import/ExcelImportController.php
<?php

namespace App\Http\Controllers\tune_orbit_bo\excel_import;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Http\Requests\tune_orbit_bo\masters\ServicesRequest;
use App\Models\masters\MasterServices;

use DB;
use Redirect;
use Auth;
use Input;


class ExcelImportController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() 
    {
      return view('tune_orbit_bo.excel_import.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

     return view('tune_orbit_bo.masters.services.create');

   }


   public function uploadExcel(Request $request)
   {
// dd($request->all());
     if($request->file('file_name')) {
      //upload an image to the /img/tmp directory and return the filepath.
      $file = Input::file('file_name');
      $tmpFilePath = 'tune_orbit_bo/service_page_excels/';
      $extension = pathinfo($file->getClientOriginalName(), PATHINFO_EXTENSION);

      $tmpFileName = time() . '.' . $extension;
      $file = $file->move($tmpFilePath, $tmpFileName);
      $path = $tmpFileName;

      $file_path=$tmpFilePath.$path;

      return response()->json(array('path'=> $file_path), 200);
    } else {
      return response()->json(false, 200);
    }
  }



    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ServicesRequest $request)
    {
      // dd($request->all());

      $request['created_by']=Auth::user()->id;
      $request['thumbnail_path']='/images/services/'.$request->temp_file_path;
      $source = "tune_orbit_bo/image/tmp/";
      $destination = getServicesDestinationPathToStore();
      if (copy($source.$request->temp_file_path, $destination.$request->temp_file_path)) {
        unlink($source.$request->temp_file_path);
      }

      MasterServices::create($request->all());

      return redirect()->route('tune_orbit_bo.masters.services.index')->with('message','Successfully Added')->with('er_type','success');  
    }

    public function deleteServiceImage(Request $request)
    {
      // dd($request->all());
      DB::table('services')->where('id',$request->service_id)->update(['thumbnail_path' => '']);
      unlink('../'.$request->path);
      return response()->json('success', 200);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

      $services=MasterServices::where('id',$id)->first();

      if($services){
        return view('tune_orbit_bo.masters.services.edit')->with('services',$services);
      }else{

       return redirect()->route('tune_orbit_bo.masters.services.index')->with('message','Cannot Edit Deactivated services')->with('er_type','danger');
     }
   }


   public function uploadImgForEdit(Request $request)
  {
     //dd($request->all());

    if($request->file('file_name')) {
      //upload an image to the /img/tmp directory and return the filepath.
      $file = Input::file('file_name');
      $tmpFilePath = 'tune_orbit_bo/image/tmp/';
      $extension = pathinfo($file->getClientOriginalName(), PATHINFO_EXTENSION);

      $tmpFileName = round(microtime(true) * 1000) . '.' . $extension;
      $file = $file->move($tmpFilePath, $tmpFileName);
      $path = $tmpFileName;

      $file_path=getServiceUploadedTmpPath($path);

      return response()->json(array('path'=> $file_path), 200);
    } else {
      return response()->json(false, 200);
    }
  }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      // dd($request->all());
      $services=MasterServices::where('id', '=', $id)->first();
      $request['updated_by']=Auth::user()->id;

      $request['thumbnail_path']='/images/services/'.$request->temp_file_path;
      $source = "tune_orbit_bo/image/tmp/";
      $destination = getServicesDestinationPathToStore();
      if (copy($source.$request->temp_file_path, $destination.$request->temp_file_path)) {
        unlink($source.$request->temp_file_path);
      }

      $services->update($request->all());
      return redirect()->route('tune_orbit_bo.masters.services.index')->with('message','Successfully Updated')->with('er_type','success');
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    public function deactivate($id)
    {
     $services=MasterServices::where('id', '=', $id)->first();
     if($services){
      $services->delete();
      return redirect()->route('tune_orbit_bo.masters.services.index')->with('message','Successfully deactivated')->with('er_type','danger');
    }else{
      $services=MasterServices::onlyTrashed()->where('id', '=', $id)->first();
      $services->restore();
      return redirect()->route('tune_orbit_bo.masters.services.index')->with('message','Successfully activated')->with('er_type','success ');
    }
  }
}

resources/views/tune_orbit_bo/layouts/dashboard.blade.php
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
    <meta charset="UTF-8">
    <title> @yield('page_title',"Tune Orbit - BO")</title>
    <meta name="_token" content="{!! csrf_token() !!}" /> 
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap 3.3.2 -->
    <link href="{{ asset("/tune_orbit_bo/admin-lte/bootstrap/css/bootstrap.min.css") }}" rel="stylesheet" type="text/css" media="all" />
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Ionicons -->
    <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="{{ asset("/tune_orbit_bo/admin-lte/dist/css/AdminLTE.css")}}" rel="stylesheet" type="text/css" />
    <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect.
    -->
    <link href="{{ asset("/tune_orbit_bo/css/bootstrap-select.min.css")}}" rel="stylesheet" type="text/css" />
    <link href="{{ asset("/tune_orbit_bo/admin-lte/dist/css/skins/skin-blue.min.css")}}" rel="stylesheet" type="text/css" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

</head>
<body class="skin-blue">
<div class="wrapper">

    <!-- Header -->
    @include('tune_orbit_bo.layouts.header')

    <!-- Sidebar -->
    @include('tune_orbit_bo.layouts.sidebar')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                @yield('page_title','Tune Orbit - BO')
                <small> @yield('page_title_sub','')</small>
            </h1>
            <!-- You can dynamically generate breadcrumbs here -->
            {{-- <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
                <li class="active">Here</li>
            </ol> --}}
        </section>

        <!-- Main content -->
        <section class="content">
            <!-- Your Page Content Here -->
            @yield('content')
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->

    <!-- Footer -->
    @include('tune_orbit_bo.layouts.footer')

</div><!-- ./wrapper -->
@section('script')
<!-- REQUIRED JS SCRIPTS -->

<!-- jQuery 2.1.3 -->
<script src="{{ asset ("/tune_orbit_bo/tinymce/js/tinymce/tinymce.min.js") }}"></script>
<script src="{{ asset ("/tune_orbit_bo/admin-lte/plugins/jQuery/jQuery-2.1.4.min.js") }}"></script>
<!-- Bootstrap 3.3.2 JS -->
<script src="{{ asset ("/tune_orbit_bo/admin-lte/bootstrap/js/bootstrap.min.js") }}" type="text/javascript"></script>
<script src="{{ asset ("/tune_orbit_bo/admin-lte/plugins/slimScroll/jquery.slimscroll.min.js") }}"></script>
<script src="{{ asset ("/tune_orbit_bo/admin-lte/plugins/fastclick/fastclick.min.js") }}"></script>
<script src="{{ asset ("/tune_orbit_bo/admin-lte/plugins/notify/bootstrap-notify.min.js") }}"></script>
<script src="{{ asset ("/tune_orbit_bo/js/jquery.validate.js") }}"></script>

<!-- AdminLTE App -->
<script src="{{ asset ("/tune_orbit_bo/js/bootstrap-select.min.js") }}"></script>
<script src="{{ asset ("/tune_orbit_bo/admin-lte/dist/js/app.min.js") }}" type="text/javascript"></script>
<script src="{{ asset ("/tune_orbit_bo/js/defaults.js") }}" type="text/javascript"></script>
<script src="{{ asset ("/tune_orbit_bo/js/multifilter.js") }}" type="text/javascript"></script>
<script src="{{ asset ("/tune_orbit_bo/js/printThis.js") }}" type="text/javascript"></script>
<script src="{{ asset ("/tune_orbit_bo/js/moment.js") }}" type="text/javascript"></script>
<script type="text/javascript">
  $(function(){
     $('[data-toggle="popover"]').popover(); 
     $('#service_id').selectpicker();
  });
</script>
 @show
 
</body>
</html>

resources/views/tune_orbit_bo/layouts/footer.blade.php
<footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
    Powered By <a href="http://www.dooziesoft.com" target="_blank">DoozieSoft</a>
    </div>
    <!-- Default to the left -->
    <strong>Copyright © 2016 <a href="#" target="_blank">Tune Orbit - BO</a>. </strong> All rights reserved.
</footer>

resources/views/tune_orbit_bo/layouts/header.blade.php
<!-- Main Header -->
<header class="main-header">

    <!-- Logo -->
    <a href="/" class="logo"><b></b>Tune Orbit - BO</a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">

                <li class="dropdown user user-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <!-- The user image in the navbar-->
                        <img src="{{ asset("/tune_orbit_bo/admin-lte/dist/img/TuneOrbit_logo.png") }}" class="user-image" alt="User Image"/>
                        <!-- hidden-xs hides the username on small devices so only the image appears. -->
                        <span class="hidden-xs">{!! Auth::user()->name !!}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- The user image in the menu -->
                        <li class="user-header">
                            <img src="{{ asset("/tune_orbit_bo/admin-lte/dist/img/TuneOrbit_logo.png") }}" class="img-circle" alt="User Image" />
                            <p style="text-align:center">
                                www.tuneorbit.com
                                <small>2016</small>
                            </p>
                        </li>
                        <!-- Menu Body -->
                        {{-- <li class="user-body">
                            <div class="col-xs-4 text-center">
                                <a href="#">Followers</a>
                            </div>
                            <div class="col-xs-4 text-center">
                                <a href="#">Sales</a>
                            </div>
                            <div class="col-xs-4 text-center">
                                <a href="#">Friends</a>
                            </div>
                        </li> --}}
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            {{-- <div class="pull-left"><a href="#" class="btn btn-default btn-flat">Profile</a></div> --}}
                            <div style="padding-left:100px;">
                                <a href="{{URL::route('sign_out')}}" class="btn btn-default btn-flat">Sign out</a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/tune_orbit_bo/layouts/sidebar.blade.php
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ asset("/tune_orbit_bo/admin-lte/dist/img/TuneOrbit_logo.png") }}" class="img-circle" alt="User Image" />
            </div>
            <div class="pull-left info">
                <p>{!! Auth::user()->name !!}</p>
                <!-- Status -->
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <!-- search form (Optional) -->
        {{-- <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
<span class="input-group-btn">
  <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
</span>
            </div>
        </form> --}}
        <!-- /.search form -->

        <!-- Sidebar Menu -->
        <ul class="sidebar-menu">
            <li class="header">Main Menu</li>
            <!-- Optionally, you can add icons to the links -->
            <li><a href="{{URL::route('dashboard')}}"><span>Dashboard</span></a></li>

            <li ><a href="{{URL::route('tune_orbit_bo.excel_import.import.index')}}"><span> Excel Import Services</span></a></li>
      
            <li><a href="{{URL::route('tune_orbit_bo.service_page.services.index')}}">New Services</a></li>
            
            <li><a href="{{URL::route('tune_orbit_bo.service_page.view_and_commit.index')}}">Commit Service Page</a></li>
            
            <li><a href="{{URL::route('tune_orbit_bo.service_page.audit_and_commit.index')}}">Audit Service Page</a></li>
            
            <li><a href="{{URL::route('tune_orbit_bo.service_page.manage_services.index')}}">Manage Services</a></li>
                
            

          

             <li class="treeview">
                <a href="#"><span><i class=" fa fa-user"></i> Masters</span> <i class="fa fa-angle-left pull-right"></i></a>
                <ul class="treeview-menu">
                <li><a href="{{URL::route('tune_orbit_bo.masters.services.index')}}">Services</a></li>
                    <li><a href="{{URL::route('tune_orbit_bo.masters.sub_services.index')}}">Sub Services</a></li>
                   
                </ul>
            </li>


             
                   
                </ul>
    </section>
    <!-- /.sidebar -->
</aside>