app/Http/routes.php
<?php
//Common Routes
Route::when('*', ['middleware' => 'csrf'], ['POST', 'PUT', 'PATCH', 'DELETE']);

Route::get('/',['as' => 'home','uses'=>'tune_orbit_bo\DashboardController@index','middleware'=>'auth']);

//Auth
Route::group(['namespace'=>'Auth'], function () {
  Route::get('login',['as' => 'login','uses'=>'AuthController@showLogin']);
  Route::post('login',['as' => 'postLogin','uses'=>'AuthController@doLogin']);
  Route::get('sign_out',['as' => 'sign_out','uses'=>'AuthController@signOut']);
});

//tune_orbit-bo  Routes
Route::group(['prefix'=>'tune_orbit_bo','namespace'=>'tune_orbit_bo','middleware'=>'auth'],function(){
  //Dashboard
  Route::get('dashboard',['as' => 'dashboard','uses'=>'DashboardController@index']);



  //Service Page
  Route::group(['prefix'=>'service_page','namespace'=>'service_page'],function(){

    //Services
   Route::resource('services','ServicePageController');

   Route::post('/update_new_service_page/{services_id}', ['as' => 'service_page.services.updateServicePage', 'uses' => 'ServicePageController@updateServicePage']);
   Route::get('/get_specific_subservices/{services_id}', ['as' => 'service_page.services.getspecificSubservices', 'uses' => 'ServicePageController@getspecificSubservices']);
   Route::get('/serviceImg_delete/', ['as' => 'service_page.services.deleteSpecificImg', 'uses' => 'ServicePageController@deleteSpecificImg']);
   Route::get('/servicePagePhoto_delete/', ['as' => 'service_page.services.deleteSpecificServicePagePhoto', 'uses' => 'ServicePageController@deleteSpecificServicePagePhoto']);

   Route::resource('view_and_commit','ViewCommitController');
   Route::put('/update_service_page/{services_id}', ['as' => 'service_page.view_and_commit.updateServicePage', 'uses' => 'ViewCommitController@updateServicePage']);

   Route::resource('audit_and_commit','AuditCommitController');
   Route::post('/audit_and_commit/{audit_checkpoint_id}/{user_service_id}', ['as' => 'getspecificServiceAuditRemark', 'uses' => 'AuditCommitController@getspecificRemark']);
   Route::post('/updateOpenHours', ['as' => 'updateOpenHours', 'uses' => 'AuditCommitController@updateOpenHours']);

      Route::resource('manage_services','ManageServicePageController');
    Route::post('/manage_services/filter', ['as' => 'service_page.manage_services.filter', 'uses' => 'ManageServicePageController@filter']);

      Route::post('/update_manage_service_page/{services_id}', ['as' => 'service_page.manage_services.updateServicePage', 'uses' => 'ManageServicePageController@updateServicePage']);

      Route::get('/manage_services/push_pull_service/{services_id}', ['as' => 'service_page.manage_services.push_pull_service', 'uses' => 'ManageServicePageController@push_pull_service']);
 });

  Route::group(['prefix'=>'excel_import','namespace'=>'excel_import'],function(){

    //Services
   Route::resource('import','ExcelImportController');

   Route::post('/uploadExcel/', ['as' => 'tune_orbit_bo.excel_import.import.uploadExcel', 'uses' => 'ExcelImportController@uploadExcel']);

 });

//Masters
  Route::group(['prefix'=>'masters','namespace'=>'masters'],function(){

    //Services
   Route::resource('services','ServicesController');

   Route::post('/upload/', ['as' => 'tune_orbit_bo.masters.services.uploadImg', 'uses' => 'ServicesController@uploadImg']);

   Route::put('/uploadImage/', ['as' => 'tune_orbit_bo.masters.services.uploadImgForEdit', 'uses' => 'ServicesController@uploadImgForEdit']);

   Route::get('/delete_image/', ['as' => 'tune_orbit_bo.masters.services.deleteServiceImage', 'uses' => 'ServicesController@deleteServiceImage']);

   Route::get('/services/deactivate/{services_id}', ['as' => 'masters.services.deactivate', 'uses' => 'ServicesController@deactivate']);



    //Sub Services
   Route::resource('sub_services','SubServicesController');
   
   Route::get('/sub_services/deactivate/{sub_services_id}', ['as' => 'masters.sub_services.deactivate', 'uses' => 'SubServicesController@deactivate']); 

   Route::get('/sub_services/manage_gallery/{sub_services_id}', ['as' => 'masters.sub_services.manage_gallery', 'uses' => 'SubServicesController@manage_gallery']); 


   Route::post('/sub_services/{sub_services_id}', ['as' => 'sub_services.updateServiceImages', 'uses' => 'SubServicesController@updateServiceImages']);

   Route::get('/serviceImg_delete/', ['as' => 'masters.sub_services.deleteSpecificServiceImg', 'uses' => 'SubServicesController@deleteSpecificServiceImg']);

   Route::post('/upload_serviceImg/', ['as' => 'tune_orbit_bo.masters.sub_services.uploadserviceImg', 'uses' => 'SubServicesController@uploadserviceImg']);

   Route::post('/edit_upload_serviceImg/', ['as' => 'tune_orbit_bo.masters.sub_services.editUploadserviceImg', 'uses' => 'SubServicesController@editUploadserviceImg']);




 });



});

function getDateDifferenceInDays($date1,$date2){
  $date1=new Date($date1);
  $date2=new Date($date2);
  $diff = new Date($date1 - $date2);
  $days = $diff/1000/60/60/24;
  $x=($days.toString()).split('.');
  return $x[0];
}

function getFormatedDate($date){
  $formated_date=date("d F Y",strtotime($date));
  return $formated_date;
}


function getServiceUploadedTmpPath($file){
  $file_path='';
  if (App::environment('local')) {
    $file_path='/tune_orbit_bo/image/tmp/'.$file;
  } else{
    $file_path=ENV('DOMAIN_PATH').'/backoffice/tune_orbit_bo/image/tmp/'.$file;
  }
  return $file_path;
}

function getServicesDestinationPathToStore(){
  $file_path='';
  if (App::environment('local')) {
    $file_path='../../../dev/tune_orbit_web/app/images/services/';
  } else{
    $file_path=ENV('DOMAIN_PATH').'../images/services/';
  }
  return $file_path;
}


function getServicesUploadedPath($file){
  $file_path='';
  if (App::environment('local')) {
    $file_path='../../../dev/tune_orbit_web/app'.$file;
  } else{
    $file_path=ENV('DOMAIN_PATH').$file;
  }
  return $file_path;
}


function getSubServiceUploadedTmpPath($file){
  $file_path='';
  if (App::environment('local')) {
    $file_path='/tune_orbit_bo/image/tmp/'.$file;
  } else{
    $file_path=ENV('DOMAIN_PATH').'/backoffice/tune_orbit_bo/image/tmp/'.$file;
  }
  return $file_path;
}


function getServicesPageBannerPath(){
  $file_path='';
  if (App::environment('local')) {
    $file_path='/tune_orbit_bo/image/service_page_images/banner';
  } else{
    $file_path=ENV('DOMAIN_PATH');
  }
  return $file_path;
}

function getServicesPageThumbnailPath(){
  $file_path='';
  if (App::environment('local')) {
    $file_path='/tune_orbit_bo/image/service_page_images/thumbnail';
  } else{
    $file_path=ENV('DOMAIN_PATH');
  }
  return $file_path;
}

function getServicesPagePhotoPath(){
  $file_path='';
  if (App::environment('local')) {
    $file_path='/tune_orbit_bo/image/service_page_images';
  } else{
    $file_path=ENV('DOMAIN_PATH').'/tune_orbit_bo/image/services/'.$file;
  }
  return $file_path;
}

app/Models/masters/AuditCheckpoint.php
<?php

namespace App\Models\masters;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class AuditCheckpoint extends Model
{
   use SoftDeletes;
   protected $dates = ['deleted_at'];
   protected $fillable = ['checkpoint','mandatory_flag'];
}

app/Models/masters/MasterServiceImages.php
<?php

namespace App\Models\masters;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class MasterServiceImages extends Model
{
      use SoftDeletes;
   protected $table='service_images';
   protected $dates = ['deleted_at'];

   protected $fillable = [
   'sub_service_id','path'
   ];
}

app/Models/masters/MasterServices.php
<?php

namespace App\Models\masters;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class MasterServices extends Model
{
      use SoftDeletes;
   protected $table='services';
   protected $dates = ['deleted_at'];

   protected $fillable = [
   'name','description','thumbnail_path','created_by','updated_by'
   ];
}

app/Models/masters/MasterSubServices.php
<?php

namespace App\Models\masters;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class MasterSubServices extends Model
{
      use SoftDeletes;
   protected $table='sub_services';
   protected $dates = ['deleted_at'];

   protected $fillable = [
   'name','service_id','description','thumbnail_path','created_by','updated_by'
   ];
}

app/Http/Controllers/tune_orbit_bo/masters/ServicesController.php
<?php

namespace App\Http\Controllers\tune_orbit_bo\masters;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Http\Requests\tune_orbit_bo\masters\ServicesRequest;
use App\Models\masters\MasterServices;

use DB;
use Redirect;
use Auth;
use Input;


class ServicesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() 
    {
      $services=DB::table('services AS sm')
      ->join('backoffice_users AS u','sm.created_by','=','u.id')
      ->leftjoin('backoffice_users AS u1','sm.updated_by','=','u1.id')
      ->select('sm.*','u.name AS created_by','u1.name AS updated_by')
      ->orderBy('sm.name','ASC')
      ->get();

      return view('tune_orbit_bo.masters.services.index')->with('services',$services);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

     return view('tune_orbit_bo.masters.services.create');

   }


   public function uploadImg(Request $request)
   {

     if($request->file('file_name')) {
      //upload an image to the /img/tmp directory and return the filepath.
      $file = Input::file('file_name');
      $tmpFilePath = 'tune_orbit_bo/image/tmp/';
      $extension = pathinfo($file->getClientOriginalName(), PATHINFO_EXTENSION);

      $tmpFileName = round(microtime(true) * 1000) . '.' . $extension;
      $file = $file->move($tmpFilePath, $tmpFileName);
      $path = $tmpFileName;

      $file_path=getServiceUploadedTmpPath($path);

      return response()->json(array('path'=> $file_path), 200);
    } else {
      return response()->json(false, 200);
    }
  }



    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ServicesRequest $request)
    {
      // dd($request->all());

      $request['created_by']=Auth::user()->id;
      $request['thumbnail_path']='/images/services/'.$request->temp_file_path;
      $source = "tune_orbit_bo/image/tmp/";
      $destination = getServicesDestinationPathToStore();
      if (copy($source.$request->temp_file_path, $destination.$request->temp_file_path)) {
        unlink($source.$request->temp_file_path);
      }

      MasterServices::create($request->all());

      return redirect()->route('tune_orbit_bo.masters.services.index')->with('message','Successfully Added')->with('er_type','success');  
    }

    public function deleteServiceImage(Request $request)
    {
      // dd($request->all());
      DB::table('services')->where('id',$request->service_id)->update(['thumbnail_path' => '']);
      unlink('../'.$request->path);
      return response()->json('success', 200);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

      $services=MasterServices::where('id',$id)->first();

      if($services){
        return view('tune_orbit_bo.masters.services.edit')->with('services',$services);
      }else{

       return redirect()->route('tune_orbit_bo.masters.services.index')->with('message','Cannot Edit Deactivated services')->with('er_type','danger');
     }
   }


   public function uploadImgForEdit(Request $request)
  {
     //dd($request->all());

    if($request->file('file_name')) {
      //upload an image to the /img/tmp directory and return the filepath.
      $file = Input::file('file_name');
      $tmpFilePath = 'tune_orbit_bo/image/tmp/';
      $extension = pathinfo($file->getClientOriginalName(), PATHINFO_EXTENSION);

      $tmpFileName = round(microtime(true) * 1000) . '.' . $extension;
      $file = $file->move($tmpFilePath, $tmpFileName);
      $path = $tmpFileName;

      $file_path=getServiceUploadedTmpPath($path);

      return response()->json(array('path'=> $file_path), 200);
    } else {
      return response()->json(false, 200);
    }
  }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      // dd($request->all());
      $services=MasterServices::where('id', '=', $id)->first();
      $request['updated_by']=Auth::user()->id;

      $request['thumbnail_path']='/images/services/'.$request->temp_file_path;
      $source = "tune_orbit_bo/image/tmp/";
      $destination = getServicesDestinationPathToStore();
      if (copy($source.$request->temp_file_path, $destination.$request->temp_file_path)) {
        unlink($source.$request->temp_file_path);
      }

      $services->update($request->all());
      return redirect()->route('tune_orbit_bo.masters.services.index')->with('message','Successfully Updated')->with('er_type','success');
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    public function deactivate($id)
    {
     $services=MasterServices::where('id', '=', $id)->first();
     if($services){
      $services->delete();
      return redirect()->route('tune_orbit_bo.masters.services.index')->with('message','Successfully deactivated')->with('er_type','danger');
    }else{
      $services=MasterServices::onlyTrashed()->where('id', '=', $id)->first();
      $services->restore();
      return redirect()->route('tune_orbit_bo.masters.services.index')->with('message','Successfully activated')->with('er_type','success ');
    }
  }
}

resources/views/tune_orbit_bo/masters/sub_services/_form.blade.php
<div class="col-md-4">
 <div class="form-group @if($errors->first('service_id')) has-error @endif">

   {!!Form::label('service_id','Service Name*')!!}
   {!! Form::servicesSelect('service_id',null) !!}
   <small class="text-danger">{{ $errors->first('service_id') }}</small>

 </div>
</div>


<div class="col-md-4">
  <div class="form-group @if($errors->first('name')) has-error @endif">
   {!!Form::label('name','Name')!!}
   {!!Form::text('name',Input::old('name'),['class' => 'form-control required','id'=>'name',"data-toggle"=>"popover","data-trigger"=>"focus","title"=>"","data-content"=>"Enter Name","data-placement"=>"bottom",])!!}
   <small class="text-danger">{{ $errors->first('name') }}</small>
 </div>
</div>


<div class="col-md-4">
  <div class="form-group @if($errors->first('description')) has-error @endif">
   {!!Form::label('description','Description')!!}
   {!!Form::textarea('description',Input::old('description'),['class' => 'form-control','id'=>'description',"data-toggle"=>"popover","data-trigger"=>"focus","title"=>"","data-content"=>"Enter description","data-placement"=>"bottom","rows"=>3])!!}
   <small class="text-danger">{{ $errors->first('description') }}</small>
 </div>
</div>

<!-- Attach Image field -->
<!-- <div class="col-md-6" id="attachment_div">
  {!! Form::label('Thumbnail Path') !!}
  <input type="file" class="form-control required" id="file_name" name="file_name">
</div>

<div class="col-md-2" style="margin-top:25px;">
  {!! Form::button('Upload Image', ['class' => 'btn btn-block btn-primary btn-block', 'id' => 'upload_btn']) !!}
</div>

<div class="clearfix" ></div>

<div class="col-md-12" id="details_div" hidden style="margin-top:25px;">

 <div class="col-md-8">
  <iframe src="" id="disp_round_attachment" height="650px" width="600px"></iframe>
</div>
</div> -->


<div class='clearfix' style="margin-top:25px;"></div>
<div class="col-md-2 pull-right">
<a href="{{URL::route('tune_orbit_bo.masters.sub_services.index')}}">{!! Form::button('Cancel', ['class' => 'btn btn-block btn-danger btn-block','id'=>'clr-btn']) !!}</a>
</div>
<div class="col-md-2 pull-right">
  <div class="form-group">
    {!! Form::submit($submitButtonText, ['class' => 'btn btn-block btn-success btn-block']) !!}
  </div>
</div>


@section('script')
@parent
<script type="text/javascript">
  $(function(){

  });
</script>
@stop

resources/views/tune_orbit_bo/masters/sub_services/create.blade.php
@extends('tune_orbit_bo.layouts.dashboard')

@section('title', 'Sub Services Master')

@section('page_title_sub', 'Add Sub Services Master')

@section('content')
<div class='row'>
  <div class='col-md-12'>
    <!-- Box -->
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Add Sub Services Here</h3>
        <div class="box-tools pull-right">
          <button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
          {{-- <button class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove"><i class="fa fa-times"></i></button> --}}
        </div>
      </div>
      <div class="box-body table-responsive no-padding">
        <div class="clearfix"></div>
        <div class="col-md-12">
          {!!Form::open(array('route' => array('tune_orbit_bo.masters.sub_services.store'), 'method' => 'POST','files'=>true,'id'=>'add-form','onsubmit'=>'return validate()'))!!}
          
          @include('tune_orbit_bo.masters.sub_services._form',['submitButtonText'=>'Save'])


          <div class='clearfix'></div>


          {!!Form::close()!!}
        </div>
        <div class="box-footer">

        </div><!-- /.box-footer-->
      </div><!-- /.box -->
    </div><!-- /.col -->

  </div>
</div><!-- /.row -->
@endsection
@section('script')
@parent
<script type="text/javascript">
  $(function(){
   $('[data-toggle="popover"]').popover(); 

   @if(Session::has('message'))
   $.notify("{{Session::get('message')}}",{
    type:'{{Session::get("er_type")}}',
  });
   @endif


  

 });


  function validate()
  {
    if($('#add-form').valid()){
      return true;
    }else{
      return false;
    }
  }

</script>
@stop

resources/views/tune_orbit_bo/masters/sub_services/edit.blade.php
@extends('tune_orbit_bo.layouts.dashboard')

@section('title', 'Sub Services Master')

@section('page_title_sub', 'Edit Sub Services Master')

@section('content')
<div class='row'>
  <div class='col-md-12'>
    <!-- Box -->
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Edit Sub Services Here</h3>
        <div class="box-tools pull-right">
          <button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
          {{-- <button class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove"><i class="fa fa-times"></i></button> --}}
        </div>
      </div>
      <div class="box-body table-responsive no-padding">
        <div class="clearfix"></div>
        <div class="col-md-12">
          {!!Form::model($sub_services,array('route' => array('tune_orbit_bo.masters.sub_services.update', $sub_services->id), 'method' => 'PUT','files'=>true,'id'=>'edit-form','onsubmit'=>'return validate()'))!!}
          
          @include('tune_orbit_bo.masters.sub_services._form',['submitButtonText'=>'Save'])


          <div class='clearfix'></div>


          {!!Form::close()!!}
        </div>
        <div class="box-footer">

        </div><!-- /.box-footer-->
      </div><!-- /.box -->
    </div><!-- /.col -->

  </div>
</div><!-- /.row -->
@endsection
@section('script')
@parent
<script type="text/javascript">
  $(function(){
   $('[data-toggle="popover"]').popover(); 

   @if(Session::has('message'))
   $.notify("{{Session::get('message')}}",{
    type:'{{Session::get("er_type")}}',
  });
   @endif


  

 });


  function validate()
  {
    if($('#edit-form').valid()){
      return true;
    }else{
      return false;
    }
  }

</script>
@stop

resources/views/tune_orbit_bo/masters/sub_services/index.blade.php
@extends('tune_orbit_bo.layouts.dashboard')

@section('title', 'Sub Services Master')

@section('page_title_sub', 'Manage Sub Services Master')

@section('content')
<div class='row'>
  <div class='col-md-12'>
    <!-- Box -->
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">List of Sub Services</h3>
        <div class="box-tools pull-right">
          <button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
          {{-- <button class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove"><i class="fa fa-times"></i></button> --}}
        </div>
      </div>

      <div class="box-body table-responsive no-padding">
        
        <div class="clearfix"></div>
        <div class="col-md-12">
          <div class="pull-right">

             <a class="btn bg-green margin" href="{{route('tune_orbit_bo.masters.sub_services.create')}}" data-toggle="tooltip" data-placement="bottom" title="Click here to add New Sub Services">
             <i class="glyphicon glyphicon-pencil"></i> Add Sub Services
           </a> 

           <a type="button" class="btn bg-navy margin" id="edit_btn" onclick="no_select()"  data-toggle="tooltip" data-placement="bottom" title="Select a row from below table and then Click Edit">
            <i class="glyphicon glyphicon-edit"></i> Edit Sub Services
          </a>

          <a type="button" class="btn bg-maroon margin" id="manage_gallery" onclick="no_select()"  data-toggle="tooltip" data-placement="bottom" title="Select a row from below table and then Click Manage Gallery">
            <i class="glyphicon glyphicon-edit"></i> Manage Gallery
          </a>
           
          <a type="button" class="btn bg-red margin" onclick="no_select()" id="deactivate_btn" data-toggle="tooltip" data-placement="bottom" title="Select a row from below table and then Click Activate/De-Activate">
            <i class="glyphicon glyphicon-trash"></i> Activate/Deactivate
          </a>

         
        </div><div class="clearfix"></div>
        <table class="table table-bordered" id="view">
          <thead>
            <tr class="bg-blue">
              <th></th>
              <th>Sub Services</th>
              <th>Services Name</th>
              <th>Description</th>         
              <th>Created by</th>
              <th>Created on</th>
              <th>Updated by</th>
              <th>Updated on</th>
              <th>Status</th>
             
            </tr>  

            <tr tr class="bg-blue">
            <th></th>
            <th><input type="text" class="form-control filter" data-col="Sub Services"></th>
            <th><input type="text" class="form-control filter" data-col="Services Name"></th>
            <th><input type="text" class="form-control filter" data-col="Description"></th>
            <th><input type="text" class="form-control filter" data-col="Created by"></th>
            <th><input type="text" class="form-control filter" data-col="Created on"></th>
            <th><input type="text" class="form-control filter" data-col="Updated by"></th>
            <th><input type="text" class="form-control filter" data-col="Updated on"></th>
            <th></th>
             </tr>
        </thead>
          <tbody>
            @foreach($sub_services as $s)
            <tr>
              <td><input type="radio" id='{{$s->id}}' name='ch'></td>
              
              <td>{{$s->name}}</td>
              <td>{{$s->services_name}}</td>
              <td>{{$s->description}}</td>
              <td>{{$s->created_by}}</td>
              <td>{{getFormatedDate($s->created_at)}}</td>
              <td>{{$s->updated_by}}</td>
              <td>{{getFormatedDate($s->updated_at)}}</td>
              @if($s->deleted_at==null)
              <td><i class="fa fa-check text-green"></i></td>
              @else
              <td><i class="fa fa-times-circle-o text-red"></i></td>
              @endif
            </tr>
            @endforeach
          </tbody>
        </table>
      <div class="clearfix"></div>

        <div class="clearfix"></div>
        
        
      </div>
      <div class="box-footer">
        {{-- <form action='#'>
        <input type='text' placeholder='New task' class='form-control input-sm' />
      </form> --}}
    </div><!-- /.box-footer-->
  </div><!-- /.box -->
</div><!-- /.col -->


</div><!-- /.row -->
@endsection

@section('script')
@parent

<script type="text/javascript">

 $(function(){
  $('.filter').multifilter({'target':$('#view')});
  $('input[name=ch]:radio').attr('checked',false);
  $('input[name=ch]:radio').change(function(){
    var id=$(this).attr('id');
    var status=$(this).attr('status');
    $("#edit_btn").attr('href',"{{URL::to('/')}}/tune_orbit_bo/masters/sub_services/"+id+"/edit");
    $("#edit_btn").attr('onclick',"");

     // $("#manage_gallery").attr('href',"{{URL::to('/')}}/tune_orbit_bo/masters/sub_services/"+id+"/manage_gallery");
      $("#manage_gallery").attr('href',"{{URL::to('/')}}/tune_orbit_bo/masters/sub_services/manage_gallery/"+id);
      
    $("#manage_gallery").attr('onclick',"");

    $("#deactivate_btn").attr('href',"{{URL::to('/')}}/tune_orbit_bo/masters/sub_services/deactivate/"+id);
    if(status){
      $("#deactivate_btn").attr('onclick',"return confirm_delete('Activate');");
    }else{
      $("#deactivate_btn").attr('onclick',"return confirm_delete('Deactivate');");
    }
    
  });
  @if(Session::has('message'))
  $.notify("{{Session::get('message')}}",{
    type:'{{Session::get("er_type")}}',
  });
  @endif
});
 function no_select(){
    $.notify("Please select row from below table",{
      type:'danger',
    });
  }
  function confirm_delete(status){
    if (!confirm('Do you really want to '+status+' sub services?')) {
    return false;
  }
}

</script>
@stop