app/Http/routes.php
<?php
//Common Routes
Route::when('*', ['middleware' => 'csrf'], ['POST', 'PUT', 'PATCH', 'DELETE']);

Route::get('/',['as' => 'home','uses'=>'tune_orbit_bo\DashboardController@index','middleware'=>'auth']);

//Auth
Route::group(['namespace'=>'Auth'], function () {
  Route::get('login',['as' => 'login','uses'=>'AuthController@showLogin']);
  Route::post('login',['as' => 'postLogin','uses'=>'AuthController@doLogin']);
  Route::get('sign_out',['as' => 'sign_out','uses'=>'AuthController@signOut']);
});

//tune_orbit-bo  Routes
Route::group(['prefix'=>'tune_orbit_bo','namespace'=>'tune_orbit_bo','middleware'=>'auth'],function(){
  //Dashboard
  Route::get('dashboard',['as' => 'dashboard','uses'=>'DashboardController@index']);



  //Service Page
  Route::group(['prefix'=>'service_page','namespace'=>'service_page'],function(){

    //Services
   Route::resource('services','ServicePageController');

   Route::post('/update_new_service_page/{services_id}', ['as' => 'service_page.services.updateServicePage', 'uses' => 'ServicePageController@updateServicePage']);
   Route::get('/get_specific_subservices/{services_id}', ['as' => 'service_page.services.getspecificSubservices', 'uses' => 'ServicePageController@getspecificSubservices']);
   Route::get('/serviceImg_delete/', ['as' => 'service_page.services.deleteSpecificImg', 'uses' => 'ServicePageController@deleteSpecificImg']);
   Route::get('/servicePagePhoto_delete/', ['as' => 'service_page.services.deleteSpecificServicePagePhoto', 'uses' => 'ServicePageController@deleteSpecificServicePagePhoto']);

   Route::resource('view_and_commit','ViewCommitController');
   Route::put('/update_service_page/{services_id}', ['as' => 'service_page.view_and_commit.updateServicePage', 'uses' => 'ViewCommitController@updateServicePage']);

   Route::resource('audit_and_commit','AuditCommitController');
   Route::post('/audit_and_commit/{audit_checkpoint_id}/{user_service_id}', ['as' => 'getspecificServiceAuditRemark', 'uses' => 'AuditCommitController@getspecificRemark']);
   Route::post('/updateOpenHours', ['as' => 'updateOpenHours', 'uses' => 'AuditCommitController@updateOpenHours']);

      Route::resource('manage_services','ManageServicePageController');
    Route::post('/manage_services/filter', ['as' => 'service_page.manage_services.filter', 'uses' => 'ManageServicePageController@filter']);

      Route::post('/update_manage_service_page/{services_id}', ['as' => 'service_page.manage_services.updateServicePage', 'uses' => 'ManageServicePageController@updateServicePage']);

      Route::get('/manage_services/push_pull_service/{services_id}', ['as' => 'service_page.manage_services.push_pull_service', 'uses' => 'ManageServicePageController@push_pull_service']);
 });

  Route::group(['prefix'=>'excel_import','namespace'=>'excel_import'],function(){

    //Services
   Route::resource('import','ExcelImportController');

   Route::post('/uploadExcel/', ['as' => 'tune_orbit_bo.excel_import.import.uploadExcel', 'uses' => 'ExcelImportController@uploadExcel']);

 });

//Masters
  Route::group(['prefix'=>'masters','namespace'=>'masters'],function(){

    //Services
   Route::resource('services','ServicesController');

   Route::post('/upload/', ['as' => 'tune_orbit_bo.masters.services.uploadImg', 'uses' => 'ServicesController@uploadImg']);

   Route::put('/uploadImage/', ['as' => 'tune_orbit_bo.masters.services.uploadImgForEdit', 'uses' => 'ServicesController@uploadImgForEdit']);

   Route::get('/delete_image/', ['as' => 'tune_orbit_bo.masters.services.deleteServiceImage', 'uses' => 'ServicesController@deleteServiceImage']);

   Route::get('/services/deactivate/{services_id}', ['as' => 'masters.services.deactivate', 'uses' => 'ServicesController@deactivate']);



    //Sub Services
   Route::resource('sub_services','SubServicesController');
   
   Route::get('/sub_services/deactivate/{sub_services_id}', ['as' => 'masters.sub_services.deactivate', 'uses' => 'SubServicesController@deactivate']); 

   Route::get('/sub_services/manage_gallery/{sub_services_id}', ['as' => 'masters.sub_services.manage_gallery', 'uses' => 'SubServicesController@manage_gallery']); 


   Route::post('/sub_services/{sub_services_id}', ['as' => 'sub_services.updateServiceImages', 'uses' => 'SubServicesController@updateServiceImages']);

   Route::get('/serviceImg_delete/', ['as' => 'masters.sub_services.deleteSpecificServiceImg', 'uses' => 'SubServicesController@deleteSpecificServiceImg']);

   Route::post('/upload_serviceImg/', ['as' => 'tune_orbit_bo.masters.sub_services.uploadserviceImg', 'uses' => 'SubServicesController@uploadserviceImg']);

   Route::post('/edit_upload_serviceImg/', ['as' => 'tune_orbit_bo.masters.sub_services.editUploadserviceImg', 'uses' => 'SubServicesController@editUploadserviceImg']);




 });



});

function getDateDifferenceInDays($date1,$date2){
  $date1=new Date($date1);
  $date2=new Date($date2);
  $diff = new Date($date1 - $date2);
  $days = $diff/1000/60/60/24;
  $x=($days.toString()).split('.');
  return $x[0];
}

function getFormatedDate($date){
  $formated_date=date("d F Y",strtotime($date));
  return $formated_date;
}


function getServiceUploadedTmpPath($file){
  $file_path='';
  if (App::environment('local')) {
    $file_path='/tune_orbit_bo/image/tmp/'.$file;
  } else{
    $file_path=ENV('DOMAIN_PATH').'/backoffice/tune_orbit_bo/image/tmp/'.$file;
  }
  return $file_path;
}

function getServicesDestinationPathToStore(){
  $file_path='';
  if (App::environment('local')) {
    $file_path='../../../dev/tune_orbit_web/app/images/services/';
  } else{
    $file_path=ENV('DOMAIN_PATH').'../images/services/';
  }
  return $file_path;
}


function getServicesUploadedPath($file){
  $file_path='';
  if (App::environment('local')) {
    $file_path='../../../dev/tune_orbit_web/app'.$file;
  } else{
    $file_path=ENV('DOMAIN_PATH').$file;
  }
  return $file_path;
}


function getSubServiceUploadedTmpPath($file){
  $file_path='';
  if (App::environment('local')) {
    $file_path='/tune_orbit_bo/image/tmp/'.$file;
  } else{
    $file_path=ENV('DOMAIN_PATH').'/backoffice/tune_orbit_bo/image/tmp/'.$file;
  }
  return $file_path;
}


function getServicesPageBannerPath(){
  $file_path='';
  if (App::environment('local')) {
    $file_path='/tune_orbit_bo/image/service_page_images/banner';
  } else{
    $file_path=ENV('DOMAIN_PATH');
  }
  return $file_path;
}

function getServicesPageThumbnailPath(){
  $file_path='';
  if (App::environment('local')) {
    $file_path='/tune_orbit_bo/image/service_page_images/thumbnail';
  } else{
    $file_path=ENV('DOMAIN_PATH');
  }
  return $file_path;
}

function getServicesPagePhotoPath(){
  $file_path='';
  if (App::environment('local')) {
    $file_path='/tune_orbit_bo/image/service_page_images';
  } else{
    $file_path=ENV('DOMAIN_PATH').'/tune_orbit_bo/image/services/'.$file;
  }
  return $file_path;
}

app/Http/Controllers/tune_orbit_bo/DashboardController.php
<?php

namespace App\Http\Controllers\tune_orbit_bo;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use DB;

class DashboardController extends Controller
{
    public function index()
    {
        $total_services=DB::table('user_services as us')->whereNull('us.deleted_at')->count();
        $pending_commit=DB::table('user_services as us')->where('us.commit_flag',0)->count();
        $pending_audit=DB::table('user_services as us')->where('us.commit_flag',1)->where('us.audit_flag',0)->count();
        $service_in_website=DB::table('user_services as us')->where('us.in_website',1)->count();
        $unaudited_service_in_website=DB::table('user_services as us')->where('us.in_website',1)->where('us.audit_flag',0)->count();
        // dd($total_services);
        return view('tune_orbit_bo.dashboard.index')->with('total_services',$total_services)->with('pending_commit',$pending_commit)->with('pending_audit',$pending_audit)->with('service_in_website',$service_in_website)->with('unaudited_service_in_website',$unaudited_service_in_website);
    }
}

app/Http/Controllers/tune_orbit_bo/excel_import/ExcelImportController.php
<?php

namespace App\Http\Controllers\tune_orbit_bo\excel_import;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Http\Requests\tune_orbit_bo\masters\ServicesRequest;
use App\Models\masters\MasterServices;

use DB;
use Redirect;
use Auth;
use Input;


class ExcelImportController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() 
    {
      return view('tune_orbit_bo.excel_import.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

     return view('tune_orbit_bo.masters.services.create');

   }


   public function uploadExcel(Request $request)
   {
// dd($request->all());
     if($request->file('file_name')) {
      //upload an image to the /img/tmp directory and return the filepath.
      $file = Input::file('file_name');
      $tmpFilePath = 'tune_orbit_bo/service_page_excels/';
      $extension = pathinfo($file->getClientOriginalName(), PATHINFO_EXTENSION);

      $tmpFileName = time() . '.' . $extension;
      $file = $file->move($tmpFilePath, $tmpFileName);
      $path = $tmpFileName;

      $file_path=$tmpFilePath.$path;

      return response()->json(array('path'=> $file_path), 200);
    } else {
      return response()->json(false, 200);
    }
  }



    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ServicesRequest $request)
    {
      // dd($request->all());

      $request['created_by']=Auth::user()->id;
      $request['thumbnail_path']='/images/services/'.$request->temp_file_path;
      $source = "tune_orbit_bo/image/tmp/";
      $destination = getServicesDestinationPathToStore();
      if (copy($source.$request->temp_file_path, $destination.$request->temp_file_path)) {
        unlink($source.$request->temp_file_path);
      }

      MasterServices::create($request->all());

      return redirect()->route('tune_orbit_bo.masters.services.index')->with('message','Successfully Added')->with('er_type','success');  
    }

    public function deleteServiceImage(Request $request)
    {
      // dd($request->all());
      DB::table('services')->where('id',$request->service_id)->update(['thumbnail_path' => '']);
      unlink('../'.$request->path);
      return response()->json('success', 200);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

      $services=MasterServices::where('id',$id)->first();

      if($services){
        return view('tune_orbit_bo.masters.services.edit')->with('services',$services);
      }else{

       return redirect()->route('tune_orbit_bo.masters.services.index')->with('message','Cannot Edit Deactivated services')->with('er_type','danger');
     }
   }


   public function uploadImgForEdit(Request $request)
  {
     //dd($request->all());

    if($request->file('file_name')) {
      //upload an image to the /img/tmp directory and return the filepath.
      $file = Input::file('file_name');
      $tmpFilePath = 'tune_orbit_bo/image/tmp/';
      $extension = pathinfo($file->getClientOriginalName(), PATHINFO_EXTENSION);

      $tmpFileName = round(microtime(true) * 1000) . '.' . $extension;
      $file = $file->move($tmpFilePath, $tmpFileName);
      $path = $tmpFileName;

      $file_path=getServiceUploadedTmpPath($path);

      return response()->json(array('path'=> $file_path), 200);
    } else {
      return response()->json(false, 200);
    }
  }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      // dd($request->all());
      $services=MasterServices::where('id', '=', $id)->first();
      $request['updated_by']=Auth::user()->id;

      $request['thumbnail_path']='/images/services/'.$request->temp_file_path;
      $source = "tune_orbit_bo/image/tmp/";
      $destination = getServicesDestinationPathToStore();
      if (copy($source.$request->temp_file_path, $destination.$request->temp_file_path)) {
        unlink($source.$request->temp_file_path);
      }

      $services->update($request->all());
      return redirect()->route('tune_orbit_bo.masters.services.index')->with('message','Successfully Updated')->with('er_type','success');
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    public function deactivate($id)
    {
     $services=MasterServices::where('id', '=', $id)->first();
     if($services){
      $services->delete();
      return redirect()->route('tune_orbit_bo.masters.services.index')->with('message','Successfully deactivated')->with('er_type','danger');
    }else{
      $services=MasterServices::onlyTrashed()->where('id', '=', $id)->first();
      $services->restore();
      return redirect()->route('tune_orbit_bo.masters.services.index')->with('message','Successfully activated')->with('er_type','success ');
    }
  }
}

resources/views/tune_orbit_bo/service_page/index.blade.php
@extends('tune_orbit_bo.layouts.dashboard')

@section('title', 'Service Page')

@section('page_title_sub', 'Manage Service Page')

@section('content')

          
<div class='row'>
  <div class='col-md-12'>
    <!-- Box -->
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">List of Services</h3>
        <div class="box-tools pull-right">
          <button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
          {{-- <button class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove"><i class="fa fa-times"></i></button> --}}
        </div>
      </div>

      <div class="box-body table-responsive no-padding">
        
        <div class="clearfix"></div>
        <div class="col-md-12">
          <div class="pull-right">

             <a class="btn bg-maroon margin" href="{{route('tune_orbit_bo.service_page.services.create')}}" data-toggle="tooltip" data-placement="bottom" title="Click here to add New Service Page">
             <i class="glyphicon glyphicon-pencil"></i> Add Service Page
           </a> 

           <a type="button" class="btn bg-navy margin" id="edit_btn" onclick="no_select()"  data-toggle="tooltip" data-placement="bottom" title="Select a row from below table and then Click Edit">
            <i class="glyphicon glyphicon-edit"></i> Edit Service Page
          </a>

          <a type="button" class="btn bg-aqua margin" id="view_btn" onclick="no_select()"  data-toggle="tooltip" data-placement="bottom" title="Select a row from below table and then Click View">
            <i class="glyphicon glyphicon-eye-open"></i> View Service Page
          </a>
           
          <!-- <a type="button" class="btn bg-red margin" onclick="no_select()" id="deactivate_btn" data-toggle="tooltip" data-placement="bottom" title="Select a row from below table and then Click Activate/De-Activate">
            <i class="glyphicon glyphicon-trash"></i> Activate/Deactivate
          </a> -->

         
        </div><div class="clearfix"></div>
        <table class="table table-bordered" id="view">
          <thead>
            <tr class="bg-blue">
              <th></th>
              <th>Service</th>
              <th>Sub Service</th>
              <th>Business Name</th>
              <th>Address</th>
              <th>Phone Number</th>
              <th>Website</th>
            </tr>  

            <tr tr class="bg-blue">
            <th></th>
            <th><input type="text" class="form-control filter" data-col="Service"></th>
            <th><input type="text" class="form-control filter" data-col="Sub Service"></th>
            <th><input type="text" class="form-control filter" data-col="Business Name"></th>
            <th><input type="text" class="form-control filter" data-col="Address"></th>
            <th><input type="text" class="form-control filter" data-col="Phone Number"></th>
            <th><input type="text" class="form-control filter" data-col="Website"></th>
             </tr>
        </thead>
          <tbody>
            @foreach($service_pages as $sp)
            <tr>
              <td><input type="radio" id='{{$sp->id}}' name='ch'></td>
              
              <td>{{$sp->service_name}}</td>
              <td>{{$sp->sub_service_name}}</td>
              <td>{{$sp->business_name}}</td>
              <td>{{$sp->address}}</td>
              <td>{{$sp->phone_number}}</td>
              <td>{{$sp->website}}</td>

            </tr>
            @endforeach
          </tbody>
          <div class="clearfix"></div>

        </table>
     

        <div class="clearfix"></div>
        
        
      </div>
      <div class="box-footer">
        {{-- <form action='#'>
        <input type='text' placeholder='New task' class='form-control input-sm' />
      </form> --}}
    </div><!-- /.box-footer-->
  </div><!-- /.box -->
</div><!-- /.col -->


</div><!-- /.row -->
@endsection

@section('script')
@parent

<script type="text/javascript">

 $(function(){
  $('.filter').multifilter({'target':$('#view')});
  $('input[name=ch]:radio').attr('checked',false);
  $('input[name=ch]:radio').change(function(){
    var id=$(this).attr('id');
    var status=$(this).attr('status');
    $("#view_btn").attr('href',"{{URL::to('/')}}/tune_orbit_bo/service_page/services/"+id);
    $("#view_btn").attr('onclick',"");

    $("#edit_btn").attr('href',"{{URL::to('/')}}/tune_orbit_bo/service_page/services/"+id+"/edit");
    $("#edit_btn").attr('onclick',"");
    
    $("#deactivate_btn").attr('href',"{{URL::to('/')}}/tune_orbit_bo/masters/services/deactivate/"+id);
    if(status){
      $("#deactivate_btn").attr('onclick',"return confirm_delete('Activate');");
    }else{
      $("#deactivate_btn").attr('onclick',"return confirm_delete('Deactivate');");
    }
    
  });
  @if(Session::has('message'))
  $.notify("{{Session::get('message')}}",{
    type:'{{Session::get("er_type")}}',
  });
  @endif
});
 function no_select(){
    $.notify("Please select row from below table",{
      type:'danger',
    });
  }
  function confirm_delete(status){
    if (!confirm('Do you really want to '+status+' services?')) {
    return false;
  }
}

</script>
@stop